samples = 10
runtime = 30
ramp = 10
cpufreq_governor_performance = true
prep = true
jobcounts = [ 1, 3, 6 ]
workloads = [ "randread" ]
block_sizes = [ "4KiB", "32KiB", "256KiB", "1MiB"  ]
queue_depths = [ 1, 8, 128 ]