plot = [
  #["rnull", "rnull-lto"],
  ["rnull", "rnull-randstruct"],
]

[[build_configs]]
name = "rnull"
kernel_config = "rnull"
latest_rustc = true
profile = ["rnull", "ci", "release"]

#[[build_configs]]
#name = "rnull-lto"
#kernel_config = "rnull-lto"
#latest_rustc = true
#profile = ["rnull", "ci", "release"]

[[build_configs]]
name = "rnull-randstruct"
kernel_config = "rnull-randstruct"
latest_rustc = true
profile = ["rnull", "ci", "release"]
